# Set own secret  
kind: Secret
apiVersion: v1
metadata:
  name: mssql-secret
  namespace: default
stringData:
  # Password is P@ssword1$ so update it with password of your choice  
  SA_PASSWORD: "Pwd12345!"
type: Opaque