version: "3"
services:
    
    db-server:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        environment:
            SA_PASSWORD: "Pwd12345!"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
        ports:
            - "1433:1433"

    web:
        
        build: .
        ports:
            - "8080:80"
        image: "dockerkumart/secondtestapi:v2"
        



apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: secondtestapi 
spec: 
  selector: 
    matchLabels: 
      app: secondtestapi 
  replicas: 1 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: secondtestapi 
    spec: 
      containers: 
      - name: secondtestapi
        image: dockerkumart/secondtestapi:#{Build.BuildId}#
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: secondtestapi 
spec: 
  selector: 
    app: secondtestapi 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer 